### ISSUE TITLE
Create base classes for common settings

### ISSUE THREAD

**Issue by christianbumann** [cake-contrib/Cake.AzureDevOps#236]
At this time `AzureDevOpsBuildSettings` exists. For calling API functions which doesn't requires the buildid itself, it would be nice to have different settings e.g. `AzureDevOpsSettings` without the buildid (Collection, Authentication and ProjectGuid/ProjectName).

**Comment by christianbumann** [comment]
@pascalberger Is this still required as we introduced the `AzureDevOpsBuildSettings` class?

**Comment by pascalberger** [comment]
@christianbumann #254 introduces three base classes with common settings: One containing credentials, one for collection information and one for project information.
