### ISSUE TITLE
Warning for missing assembly

### ISSUE THREAD

**Issue by twenzel** [cake-contrib/Cake.AzureDevOps#353]
When using the new version (2.0.0-beta0001 or 2.0.0) I get a warning when using with Cake tool version 2.2.0 (.NET 6.0, Win10 20H2)

`Could not load C:\<myroot>\tools\Addins\Cake.AzureDevOps.2.0.0-beta0001\lib\net6.0\Microsoft.TeamFoundation.SourceControl.WebApi.dll (missing Microsoft.TeamFoundation.Policy.WebApi, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)`

**Comment by pascalberger** [comment]
I added a bunch of integration tests including one for Cake tool and .NET 6, but wasn't able yet to reproduce this error. 

@twenzel Are you able to reproduce it by adding a test to https://github.com/cake-contrib/Cake.AzureDevOps/blob/develop/tests/script-runner/net6.0/build.cake?

**Comment by pascalberger** [comment]
> I added a bunch of integration tests including one for Cake tool and .NET 6, but wasn't able yet to reproduce this error.

Nevermind, the warning appears now also in the integration tests: https://dev.azure.com/cake-contrib/Cake.AzureDevOps/_build/results?buildId=8499&view=logs&j=114e702c-1619-501e-85e4-78f6a028ff30&t=0b666fc3-9dc8-53b2-f9e1-ae759ee8f16f&l=366

**Comment by twenzel** [comment]
Sorry for my late response. Yes I get the warning also using the mentioned integration test.
