### ISSUE TITLE
Wrong description and handling in AzureDevOpsAliases.PullRequest

### ISSUE THREAD

**Issue by christianbumann** [cake-contrib/Cake.AzureDevOps#433]
The throwExceptionIfPullRequestCouldNotBeFound doesnt' seems to be correct here and in the other method above without this argument. 

https://github.com/cake-contrib/Cake.AzureDevOps/blob/681a6268911a14e4ae0e4440ad9bed322859238e/src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs#L126C26-L126C26

Imho this should be e.g. throwExceptionIfSystemAccessTokenDoesntExists

Maybe als this line doesn't make really sense on the first view. For this line the argument would be ok, but not for the handling above.... maybe there sould be a seconday argument?
https://github.com/cake-contrib/Cake.AzureDevOps/blob/681a6268911a14e4ae0e4440ad9bed322859238e/src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs#L137C1-L138C1

**Comment by christianbumann** [comment]
This line 
https://github.com/cake-contrib/Cake.AzureDevOps/blob/681a6268911a14e4ae0e4440ad9bed322859238e/src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs#L130C22-L130C22

calls this 
https://github.com/cake-contrib/Cake.AzureDevOps/blob/681a6268911a14e4ae0e4440ad9bed322859238e/src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestSettings.cs#L127C18-L127C18

and calls this
public AzureDevOpsPullRequestSettings(IAzureDevOpsCredentials credentials)

and there nowhere the overload throwExceptionIfPullRequestCouldNotBeFound will be considered

**Comment by pascalberger** [comment]
@christianbumann Can you please give some context what (from the public API) you're calling, what's the actual outcome and what would be your expectation?

**Comment by christianbumann** [comment]
> @christianbumann Before diving into implementation details, can you please give some context what (from the public API) you're calling, what's the actual outcome and what would be your expectation?

I am using this API
return this.Context.AzureDevOpsPullRequestUsingAzurePipelinesOAuthToken(false);

If there is no PullRequest, I am excepting that no Exception will be thrown as described on the API function.
This was working with Version 1.x of Cake.AzureDevOps, but not with 3.0.1
If you following the code which I described in my second comment above, you will see that this flag doesn't work anymore as expected.

**Comment by pascalberger** [comment]
@christianbumann  You used version 1.0 or 1.1 where it worked?

**Comment by christianbumann** [comment]
> @christianbumann You used version 1.0 or 1.1 where it worked?

Sorry my fault, ist was version 0.5.1
